### ISSUE TITLE
Inline Codes Inside Code Blocks

### ISSUE THREAD

**Issue by dutymess** [p3yman/benevis.online#7]
Thanks for the great tool. 

I was creating a document and noticed when I add code blocks, the text inside appear as individual inline codes.

![Screenshot_20201013_153550](https://user-images.githubusercontent.com/19936104/95858322-c8693f80-0d69-11eb-9541-89eab9ac4706.jpeg)

Also, it would be nice if the code block was LTR in the input panel. :thinking:

**Comment by p3yman** [comment]
@dutymess Thanks for the report. I'll check it and fix it ASAP. 😊
